// src/app/layout.tsx
import type { Metadata } from "next";
// Import the chosen Google Fonts
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";

// Configure Inter (sans-serif)
const inter = Inter({
  subsets: ["latin"], // Specify character subsets
  variable: "--font-inter", // Define CSS variable (new name)
  display: 'swap',
});

// Configure Roboto Mono (monospace)
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono", // Define CSS variable (new name)
  display: 'swap',
  // You might want to specify weights if needed, e.g.:
  // weight: ['400', '500', '700']
});

export const metadata: Metadata = {
  title: "Create Next App", // Update your title/description
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Apply the NEW font variable class names to the html tag
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
